# Solving-Africa-Power-Problem
African and African needs their power to be fixed. Technology is the Best, Fastest and Safest way to acheve this.
- 👋 Hi, I’m @elchilee
- 👀 I’m interested in using technology to solve the power problem in Africa using recyclable energy...
- 🌱 I’m currently learning Python coding with Simplilearn, Ethical Hacking with Simplilearn and Software Engineering with ALX...
- 💞️ I’m looking to collaborate on software development...
- 📫 How to reach me +234 07067333502, email: chileechukwu@yahoo.com...

